In [63]:
import pandas as pd
import numpy as np

In [64]:
truenews = pd.read_csv('true_dataset.csv')
fakenews = pd.read_csv('fake_dataset.csv')

In [65]:
data = pd.concat([truenews, fakenews])

In [66]:
data_final = data[['Label', 'tweet']]

In [67]:
data_final.Label.value_counts() 

HOAKS    21
FAKTA    16
Name: Label, dtype: int64

In [68]:
data_final['label_num'] = data_final.Label.map({'FAKTA': 1, 'HOAKS': 0})

/var/folders/rz/pqnzp2f91gdc909lx16dwwr80000gn/T/ipykernel_29967/2254299375.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_final['label_num'] = data_final.Label.map({'FAKTA': 1, 'HOAKS': 0})


In [69]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [70]:
#Data Cleaning
from nltk.corpus import stopwords
import string
def process_text(text: str):
    nopunc = [char for char in text if char not in string.punctuation]

    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)
    
    # Convert string to lowercase and remove stopwords
    clean_string = [word for word in nopunc.split() if word.lower() not in stopwords.words('indonesian')]
    return clean_string

In [71]:
data_final['tweet_clean'] = data_final.tweet.apply(process_text)

/var/folders/rz/pqnzp2f91gdc909lx16dwwr80000gn/T/ipykernel_29967/3050993249.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_final['tweet_clean'] = data_final.tweet.apply(process_text)


In [72]:
x = data_final.tweet
y = data_final['label_num']

x

0     apa penyebab varian baru virus corona kembali ...
1     virus corona atau covid    terus bermutasi hin...
2     kenapa varian dan subvarian baru virus corona ...
3     kenapa varian dan subvarian baru virus corona ...
4     pemerintah mewaspadai munculnya virus corona v...
5     aturan ini akan berubah bila ada varian baru v...
6     commuters  hati hati ada varian baru nih     v...
7     meski kenaikan kasus covid    di indonesia bel...
8     lawanvarianbaru  tanda  omricon varian baru  g...
9     varian baru corona omicron ba   dan ba   kini ...
10    ada varian baru virus corona  indonesia bersia...
11    jangan abai  jangan panik  tetap waspadai vari...
12     tetap harus waspada dengan virus corona varia...
13    virus grismo varian baru corona muncul di swed...
14     tetap harus waspada dengan virus corona varia...
15     tetap harus waspada dengan virus corona varia...
0     saya lebih percaya kpd dr  siti fadilah supari...
1      smoga sj bukan jd bisnis  ada yg bilang k

In [87]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)

(27,)
(10,)
(27,)


In [94]:
vec = CountVectorizer()
vec.fit(x_train)
x_train_dtm = vec.transform(x_train)
x_train_dtm = vec.fit_transform(x_train)

In [79]:
x_train_dtm

<27x231 sparse matrix of type '<class 'numpy.int64'>'
	with 408 stored elements in Compressed Sparse Row format>

In [95]:
x_test_dtm = vec.transform(x_test)

In [96]:
x_test_dtm

<10x231 sparse matrix of type '<class 'numpy.int64'>'
	with 70 stored elements in Compressed Sparse Row format>

In [97]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train_dtm, y_train)

MultinomialNB()

In [100]:
y_result = model.predict(x_test_dtm)

In [101]:
import pickle
pickle.dump(model, open('model.pkl', 'wb'))

In [102]:
text = "flu burung dl untuk di jadikan lahan bisnis vaksin"
x_text = vec.transform([text])

In [103]:
model.predict(x_text)

array([0])

In [99]:
y_result

array([1])

In [93]:
y_result

array([0])

In [91]:
y_result

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1])

In [104]:
pickle.dump(vec, open('vec.pkl', 'wb'))